---

- name: route53_check
  route53_check:
    hosted_zone_id: "{{ hosted_zone_id }}"
    private_zone: "{{ private_zone }}"
    zone_records: "{{ zone_records }}"
    zone_records_filter: "{{ zone_records_filter }}"
  register: check_route53_zones
  # no_log: "{{ var_no_log }}"

- name: Mount route53_zones dict used in role
  set_fact:
    route53_zones:
      - zone: "{{ zone_name }}"
        state: ignore
        records: "{{ check_route53_zones.send_to_aws | list }}"
        private_zone: "{{ check_route53_zones.private_zone }}"
        hosted_zone_id: "{{ check_route53_zones.hosted_zone_id }}"
  no_log: "{{ var_no_log }}"

- name: debug diff
  debug: msg="{{ check_route53_zones.json_diff }}"

