---
- debug: var=i_zone
- name: sleep for 10 seconds and continue with play
  wait_for: timeout=10
- route53:
    command: "{{ item.state |d('present')}}"
    zone: "{{ i_zone.zone }}"
    record: "{{ item.record }}"
    type: "{{ item.type }}"
    ttl: "{{ item.ttl | default(omit) }}"
    overwrite: "{{ item.overwrite | default(omit) }}"
    value: "{{ item.value }}"
    alias: "{{ item.alias | default(omit) }}"
    alias_hosted_zone_id: "{{ item.alias_hosted_zone_id | default(omit) }}"
    identifier: "{{ item.identifier | default(omit) }}"
    weight: "{{ item.weight | default(omit) }}"
    health_check: "{{ item.health_check | default(omit) }}"
    wait: True
  with_items:
    - "{{ i_zone.records }}"

- fail:
    msg: "There are unversioned security groups"
  when: check_route53_zones.json_diff.manual_changes | length != 0